apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: otp-sc
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
