apiVersion: v1
kind: Service
metadata:
  name: otp-backend
  namespace: otp-prod
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: metrics   # ðŸ‘ˆ IMPORTANT (string reference)
      port: 4000
      targetPort: 4000
