apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otp-ingress
  namespace: otp-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - skorganics.online
    - www.skorganics.online
    secretName: skorganics-tls
  rules:
  - host: skorganics.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: www.skorganics.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
