apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - storage/storageclass.yaml
  - config/configmap.yaml
  - config/secret.yaml
  - database/statefulset.yaml
  - database/service.yaml
  - backend/deployment.yaml
  - backend/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml
